[build]
builder = "DOCKERFILE"
dockerfilePath = "webapp/backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm run start"

# データベースマイグレーション設定
[deploy.migrate]
command = "npm run db:migrate"

[[services]]
name = "mythologia-backend"

[services.variables]
NODE_ENV = "production"
PORT = "8000"