name: PR Checks - Test & Type Check

on:
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'webapp/backend/**'
      - 'webapp/shared/**'
      - '.github/workflows/**'

jobs:
  backend-checks:
    name: Backend Tests & Type Check
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd webapp
          npm ci
      
      - name: Install backend dependencies
        run: |
          cd webapp/backend
          npm ci
      
      - name: Install shared dependencies
        run: |
          cd webapp/shared
          npm ci
      
      - name: Build shared package
        run: |
          cd webapp/shared
          npm run build
      
      - name: Run TypeScript type check
        run: |
          cd webapp/backend
          npm run type-check
      
      - name: Run tests
        run: |
          cd webapp/backend
          npm test
      
      - name: Run lint (if available)
        run: |
          cd webapp/backend
          npm run lint || echo "Lint script not available, skipping..."
        continue-on-error: true
      
      - name: Check build
        run: |
          cd webapp/backend
          npm run build || echo "Build script not available, skipping..."
        continue-on-error: true

  # コメント: 将来的にfrontendチェックも追加可能
  # frontend-checks:
  #   name: Frontend Tests & Type Check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         cache: 'npm'
  #         cache-dependency-path: 'webapp/package-lock.json'
  #     - name: Install dependencies
  #       run: |
  #         cd webapp
  #         npm ci
  #     - name: Frontend type check
  #       run: |
  #         cd webapp/frontend
  #         npm run type-check
  #     - name: Frontend tests
  #       run: |
  #         cd webapp/frontend
  #         npm test